import json
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import os

"""
This script filters ROIs to include only those within 300km of coastline.

Inclusion criteria:
- ROIs within 300km buffer of coastline (both land and sea)

Logic:
- Use coastline shapefile with 300km buffer to identify coastal ROIs
- This includes:
  a) Coastal land areas (cities, ports, beaches)
  b) Near-shore ocean areas
  c) Islands and peninsulas
- Excludes inland areas far from coast (>300km)
"""

# === Paths ===
json_file = '/home/wangyu/CCR/CCR_CoastlineCloudRemoval/JSON_analysis/combined_all_rois_all_samples.json'
output_json = '/home/wangyu/CCR/CCR_CoastlineCloudRemoval/ROI_filter/300km/combined_coastline_and_sea_300km.json'
output_roi_list = '/home/wangyu/CCR/CCR_CoastlineCloudRemoval/ROI_filter/300km/coastline_and_sea_rois_300km.txt'
metadata_file = "/home/wangyu/allclear/metadata/rois/rois_metadata.csv"
coastline_shapefile = "/home/wangyu/CCR/CCR_CoastlineCloudRemoval/coastline_shapefiles/ne_10m_coastline.shp"
data_folder = "/mnt/sdb/jingfeng/data"

print("="*80)
print("COASTLINE ROI FILTERING (300km Buffer)")
print("="*80)

# === Load JSON file ===
print("\n1. Loading JSON file...")
with open(json_file, 'r') as f:
    data = json.load(f)
print(f"   Total entries in JSON: {len(data)}")

# Extract all unique ROIs from JSON
json_rois = set()
for key, value in data.items():
    roi_id = value['roi'][0]  # e.g., "roi100488"
    roi_num = roi_id.replace('roi', '')
    json_rois.add(roi_num)
print(f"   Unique ROIs in JSON: {len(json_rois)}")

# === Load metadata CSV ===
print("\n2. Loading metadata and creating GeoDataFrame...")
df_meta = pd.read_csv(metadata_file)
print(f"   Total ROIs in metadata: {len(df_meta)}")

# === Create GeoDataFrame for ROIs ===
gdf_rois = gpd.GeoDataFrame(
    df_meta,
    geometry=[Point(lon, lat) for lon, lat in zip(df_meta['longitude'], df_meta['latitude'])],
    crs="EPSG:4326"
)

# === Load and buffer coastline ===
print("\n3. Identifying coastline ROIs (within 300km buffer)...")
gdf_coastline = gpd.read_file(coastline_shapefile)
buffer_distance = 2.70  # ~300 km in degrees
gdf_coastline_buffered = gdf_coastline.copy()
gdf_coastline_buffered['geometry'] = gdf_coastline_buffered.geometry.buffer(buffer_distance)

# Spatial join: ROIs within buffered coastline
gdf_coastline_rois = gpd.sjoin(gdf_rois, gdf_coastline_buffered, how="inner", predicate="within")
roi_column = 'roi_id'
coastline_roi_ids = set(gdf_coastline_rois[roi_column].astype(str).tolist())
print(f"   ROIs within coastline buffer (300km): {len(coastline_roi_ids)}")

# === Filter ROIs with valid folders ===
print("\n4. Checking for valid data folders...")
actual_folders = set(os.listdir(data_folder))
valid_rois_with_data = set()
for roi in coastline_roi_ids:
    if f"roi{roi}" in actual_folders:
        valid_rois_with_data.add(roi)
print(f"   ROIs with valid folders: {len(valid_rois_with_data)}")

# === Find intersection with JSON ROIs ===
print("\n5. Filtering JSON entries...")
json_valid_rois = json_rois.intersection(valid_rois_with_data)
print(f"   ROIs in JSON that meet criteria: {len(json_valid_rois)}")

# ROIs that don't meet criteria (outside 300km buffer)
rejected_rois = json_rois - valid_rois_with_data
print(f"   ROIs to be filtered out: {len(rejected_rois)}")

# === Filter JSON data ===
print("\n6. Creating filtered JSON...")
filtered_data = {}
for key, value in data.items():
    roi_id = value['roi'][0]  # e.g., "roi100488"
    roi_num = roi_id.replace('roi', '')
    
    if roi_num in valid_rois_with_data:
        filtered_data[key] = value

# === Statistics ===
print("\n" + "="*80)
print("FILTERING RESULTS")
print("="*80)
print(f"Original entries:              {len(data)}")
print(f"Filtered entries:              {len(filtered_data)}")
print(f"Removed entries:               {len(data) - len(filtered_data)}")
print(f"Removal rate:                  {(len(data) - len(filtered_data))/len(data)*100:.2f}%")
print(f"\nOriginal unique ROIs:          {len(json_rois)}")
print(f"Filtered unique ROIs:          {len(json_valid_rois)}")
print(f"Removed ROIs:                  {len(rejected_rois)}")

print(f"\n--- ROI Breakdown ---")
print(f"Coastline ROIs (300km buffer): {len(coastline_roi_ids)}")
print(f"With valid data folders:       {len(valid_rois_with_data)}")
print(f"Final in JSON:                 {len(json_valid_rois)}")
print(f"Excluded (>300km from coast):  {len(rejected_rois)}")

# === Save filtered JSON ===
print(f"\n7. Saving filtered JSON to {output_json}...")
os.makedirs(os.path.dirname(output_json), exist_ok=True)
with open(output_json, 'w') as f:
    json.dump(filtered_data, f, indent=2)

# === Save ROI list ===
print(f"\n8. Saving ROI list to {output_roi_list}...")
with open(output_roi_list, 'w') as f:
    f.write("# Coastline ROIs (within 300km buffer)\n")
    f.write(f"# Generated by: {os.path.basename(__file__)}\n")
    f.write(f"# Buffer distance: 300km (~2.70 degrees)\n")
    f.write(f"# Total ROIs: {len(valid_rois_with_data)}\n")
    f.write(f"# Includes: coastal land areas, near-shore ocean, islands\n")
    f.write(f"# Excludes: inland areas >300km from coast\n")
    f.write("#\n")
    for roi in sorted(valid_rois_with_data, key=int):
        f.write(f"{roi}\n")

print(f"\n✅ Successfully filtered JSON file!")
print(f"   JSON output: {output_json}")
print(f"   ROI list:    {output_roi_list}")

# === Show sample ROIs ===
print(f"\n📊 Sample included ROIs (first 20):")
for roi in sorted(list(valid_rois_with_data), key=int)[:20]:
    print(f"   roi{roi}")

if len(valid_rois_with_data) > 20:
    print(f"   ... and {len(valid_rois_with_data) - 20} more")

# === Show sample excluded ROIs ===
if rejected_rois:
    print(f"\n❌ Sample excluded ROIs (>300km from coast, first 20):")
    for roi in sorted(list(rejected_rois), key=int)[:20]:
        print(f"   roi{roi}")
    if len(rejected_rois) > 20:
        print(f"   ... and {len(rejected_rois) - 20} more")

print("\n" + "="*80)
print("DONE!")
print("="*80)
